# Example configuration file.

[playlist]
format = "m3u8"
paths = "relative"


[tracks]
sort = [
  ["tracknumber", "discnumber"],
  ["tracknumber"],
]

  [[tracks.blacklist."Album 1"]]
  discnumber = "1"
  tracknumber = "4"

  [[tracks.blacklist."Album 2"]]
  tracknumber = "5"

  [[tracks.blacklist."Spring Club Tour 2008"]]
  discnumber = "1"
  tracknumber = "2"


[groups]
tags = [
  # ["musicbrainz_albumid"],
  # ["album", "catalognumber"],
  ["album"],
]
fallback_name = "fallback"

  [groups.split_tags]
  "Album 1" = ["discnumber"]
  "Album 2" = ["artist", "title"]
  fallback = ["title"]

  "Airdrawndagger" = ["discnumber"]
  "Communicate" = ["discnumber"]
  "Northern Exposure" = ["discnumber"]
  "Northern Exposure 2" = ["discnumber"]
  "Northern Exposure: Expeditions" = ["discnumber"]
  "Renaissance: The Mix Collection" = ["discnumber"]
  "[non-album tracks]" = ["artist", "title"]

  [[groups.separate."Album 3"]]
  title = "Track title"

  [[groups.separate."Album 3"]]
  discnumber = "1"
  tracknumber = "11"

  [[groups.separate."Album 4"]]
  discnumber = "2"
  tracknumber = "9"

  [[groups.separate.Wip3out]]
  discnumber = "1"
  tracknumber = "13"

  [[groups.separate.Wip3out]]
  discnumber = "1"
  tracknumber = "14"

  [[groups.separate."Airdrawndagger	2"]]
  title = "Scorchio"
  tracknumber = "5"
