sudo: false

language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  # Travis-CI 'pypy' is ancient (Python 2.7.8, 2/2015), so request a newer one
  - pypy-5.4.1             # Python 2.7.10
  # Travis-CI 'pypy3' is even older (Python 3.2.5, 10/2014), so ditto
  - pypy3.3-5.2-alpha1     # Python 3.3.5
  # not working on Travis-CI as of 6/2017:
  # https://github.com/travis-ci/travis-ci/issues/7507
  # - pypy3.5-5.7.1-alpha  # Python 3.5.3

addons:
  apt:
    packages:
      - make
      - gcc
      - qemu-utils
      - xorriso
      - zlib1g-dev

before_script:
  - export PATH=$PATH:$PWD/bin
  - export PREFIX=$PWD

install:
  - pip install --upgrade pip setuptools
  - pip install tox-travis
  - pip install codecov

cache:
  apt: true
  directories:
    - $HOME/.cache/pip

script: tox

after_success:
  if [ -z "$TRAVIS_TAG" ]; then
    codecov;
  else
    echo "Tag build ($TRAVIS_TAG). Not uploading coverage.";
  fi
