---

# PiCamera options.
picamera:
    # Where to store taken pictures.
    photo_directory: "/home/pi/pimaton_pictures"
    number_of_pictures_to_take: 6
    time_before_first_picture: 4
    time_between_pictures: 2
    # Prefix for the name of the taken pictures.
    picture_prefix_name: "test_pimaton"
    # PiCamera specific settings.
    # For more information, see the PiCamera class here:
    # https://picamera.readthedocs.io/en/latest/api_camera.html
    settings:
        resolution:
            width: 560
            height: 496
        framerate: 30
        sharpness: 0
        contrast: 0
        brightness: 50
        saturation: 0
        iso: 0
        video_stabilization: False
        exposure_compensation: 0
        exposure_mode: 'auto'
        meter_mode: 'backlit'
        awb_mode: 'auto'
        rotation: 0
        hflip: True
        vflip: False
        annotate_text_size: 80

# Pimaton global options.
pimaton:
    time_between_loop: 2
    # UI mode, can be tui (Text user interface) or GUI (graphical user interface)
    # For the GUI to work, you need X and a desktop manager.
    # Only tui mode is available for now.
    ui_mode: 'tui'
    inputs:
        - "keyboard" # React on "enter" key.
        - "gui" # Only available when ui_mode us GUI.
        # - GPIO

# This section is only used if pimaton[ui_mode] is set to "gui"
gui:
    header_message: "Pimaton - Opensource PhotoBooth app for Rpi!"
    footer_message: "All pictures will be saved and sent to the newly wed, be careful ;)"
    start_btn_txt: "Let's roll!"
    thankyou_message: "Thanks for using Pimaton, your picture should be ready!"
    time_between_processing_and_thankyou_screen: 2
    time_between_thankyou_and_waiting: 5
    time_between_steps: 2

# Image options.
image:
    print_pic:
        # Prefix for the generated image.
        generated_prefix_name: "pimaton"
        # Path for the template jpg to use if any. 
        # Put empty string if no template.
        template: None
        # Directory where are stored the generated pictures.
        output_dir: "/home/pi/pimaton_pictures"
        # Width and Height of the generated image.
        width: 1241
        height: 1754
        # Columns and Rows for the generated image.
        rows: 3
        cols: 2

    # Thumbnails size.
    thumbnails:
        width: 560
        height: 496

print:
    # If pimaton should try to print the generated picture.
    enabled: false
    # The rest of the options are only needed if pimaton[enable_print] is True.
    user: 'pi'
    printer_key: 0
    app_name: 'Pimaton'
    # If Like me, your printer doesn't like receiving 2 commands too fast, 
    # you can set a timer between each print command.
    time_between_print: 5
    # If your printer works faster if you wait for the previous job to be finished.
    wait_for_finished_job: true
    # Options to path to pycups printFile method
    options:
        # Options must have string key and value, do not remove the quotes. 
        fit-to-page: 'True'
        copies: '1'
