heat_template_version: queens

description: >
  OpenStack containerized Neutron service

outputs:
  config_settings:
    description: Extra hieradata needed to log to files in the host.
    value: null
  docker_config:
    description: Extra containers needed for logging to files in the host.
    value:
      step_2: {}
  volumes:
    description: The volumes needed to log to files in the host.
    value:
      - /var/log/containers/neutron:/var/log/neutron
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value:
      - name: create persistent logs directory
        file:
          path: "{{ item }}"
          state: directory
        with_items:
          - /var/log/containers/neutron
      - name: neutron logs readme
        copy:
          dest: /var/log/neutron/readme.txt
          content: |
            Log files from neutron containers can be found under
            /var/log/containers/neutron and /var/log/containers/httpd/neutron-api.
        ignore_errors: true
