# coding: utf-8

"""
    Digitick REST API

    The Digitick REST API is a set of methods giving access to catalog, user and cart management.

    OpenAPI spec version: v1.0
    Contact: contact@digitick.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PriceCondition(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, price_id=None, group=None, quantity=None):
        """
        PriceCondition - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'price_id': 'float',
            'group': 'int',
            'quantity': 'int'
        }

        self.attribute_map = {
            'price_id': 'priceId',
            'group': 'group',
            'quantity': 'quantity'
        }

        self._price_id = price_id
        self._group = group
        self._quantity = quantity

    @property
    def price_id(self):
        """
        Gets the price_id of this PriceCondition.

        :return: The price_id of this PriceCondition.
        :rtype: float
        """
        return self._price_id

    @price_id.setter
    def price_id(self, price_id):
        """
        Sets the price_id of this PriceCondition.

        :param price_id: The price_id of this PriceCondition.
        :type: float
        """

        self._price_id = price_id

    @property
    def group(self):
        """
        Gets the group of this PriceCondition.

        :return: The group of this PriceCondition.
        :rtype: int
        """
        return self._group

    @group.setter
    def group(self, group):
        """
        Sets the group of this PriceCondition.

        :param group: The group of this PriceCondition.
        :type: int
        """

        self._group = group

    @property
    def quantity(self):
        """
        Gets the quantity of this PriceCondition.

        :return: The quantity of this PriceCondition.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """
        Sets the quantity of this PriceCondition.

        :param quantity: The quantity of this PriceCondition.
        :type: int
        """

        self._quantity = quantity

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PriceCondition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
