import os


__author__ = 'Manfred Minimair <manfred@minimair.org>'


class DefaultNames:
    default_file = 'kernel-chc.json'  # default file name for connection file
    storage_key = 'chc'
    # prefix to identify items corresponding to this application in Storage
    chconsole_config_file = 'jupyter_chconsole_config.py'
    # name of the configuration file generated by chconsole
    # located in the jupyter_core.paths.jupyter_config_dir() directory
    #
    # chrun:
    chrun_config_file = 'jupyter_chrun_config.py'
    kernel_user = 'ch_kernel'
    data_key = 'ch_tunnel'
    # key for storing data in addition to connection file keys

    # chlaunch:
    chgui_launch_config_file = 'jupyter_chgui_launch_config.py'

    # chjoin:
    chjoin_config_file = 'jupyter_chjoin_config.py'
