
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-16T12:36:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "98622ddb320fdf0f720f53ef1eca3727cc046445",
 "version": "1.6.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
