# -*- coding: utf-8 -*-

urls = [
    'https://www.google.com',
    'https://www.facebook.com',
    'https://www.reddit.com',
    'https://www.youtube.com',
    'https://www.wikipedia.org',
    'https://www.amazon.com',
    'https://www.twitter.com',
    'https://www.instagram.com',
    'https://www.linkedin.com',
    'https://www.netflix.com',
    'https://www.imgur.com',
    'https://www.ebay.com',
    'https://www.bing.com',
    'https://www.apple.com',
    'https://www.bing.com',
    'https://www.tumblr.com',
    'https://www.google.ca',
    'https://www.stackoverflow.com',
    'https://www.github.com',
    'https://www.paypal.com',
    'https://www.bbc.com',
    'https://www.quora.com',
    'https://www.walmart.com',
    'https://www.samsung.com',
    'https://www.baidu.com',
    'https://www.wordpress.org',
    'https://www.adobe.com',
    'https://www.vimeo.com',
    'https://www.w3.org',
    'https://www.wix.com',
    'https://www.wsj.com',
    'https://www.reuters.com',
    'https://www.cdc.gov',
    'https://www.webmd.com',
    'https://www.bing.com'
]

street_names = [
    'Main St.',
    'Second St.',
    'Elm',
    'Maple',
    'Park Ave.',
    'Lake Rd.',
    'Redwood',
    'Eighth St.',
    'Williams Rd.',
    'Main Blvd.',
    'Express Dr.',
    'Country Ln.',
    'Farmers Pkwy.',
    'Augusta Dr.',
    'Benton St.',
    'Brook Ct.',
    'Dexter Ave.',
    'N Frisco Ave.',
    'S Appleton Dr.',
    'S Blueridge Pl.',
    'Trail View Rd.',
    'Burlington Dr.',
    'Burrard Street Bridge'
]

domains = [
    'gmail',
    'hotmail',
    'aol',
    'outlook',
    'yahoo'
]

top_level_domains = [
    'io',
    'com',
    'ca',
    'co',
    'org',
    'gov',
    'net'
]

cities = [
    'Springfield',
    'Washington',
    'Spokane',
    'Riverside',
    'Georgetown',
    'Fresno',
    'Seattle',
    'Kansas City',
    'Rogers',
    'Bentonville',
    'Chicago',
    'Tampa Bay',
    'Austin',
    'Dallas',
    'Nashville',
    'Portland',
    'Milford',
    'Boston',
    'Reno',
    'Oakland',
    'Charleston',
    'Dover',
    'Toronto',
    'Vancouver',
    'Ontario',
    'Victoria',
    'Quebec City',
    'Montreal',
    'Winnipeg'
]


states = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AS': 'American Samoa',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'GU': 'Guam',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MP': 'Northern Mariana Islands',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NA': 'National',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'PR': 'Puerto Rico',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VI': 'Virgin Islands',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming'
}

provinces = {
    'AB': 'Alberta',
    'BC': 'British Columbia',
    'MB': 'Manitoba',
    'NB': 'New Brunswick',
    'NL': 'Newfoundland and Labrador',
    'NS': 'Nova Scotia',
    'ON': 'Ontario',
    'PE': 'Prince Edward Island',
    'QC': 'Quebec',
    'SK': 'Saskatchewan'
}

first_names = [
    'Carlos',
    'Dart',
    'Matt',
    'Jill',
    'Frank',
    'Jack',
    'Trey',
    'Karen',
    'Roy',
    'Emma',
    'Diego',
    'Juan',
    'Paul',
    'Wayne',
    'Hope',
    'Kristen',
    'Taylor',
    'Olivia',
    'Atticus',
    'Zheng',
    'Jasper',
    'Oliver',
    'Ava',
    'Janet',
    'Jane',
    'Anthony',
    'Jasmine',
    'Jordan',
    'Madison',
    'Kiara',
    'Jaylen',
    'Penny',
    'Sheldon',
    'Theo',
    'Ruby',
    'Emily',
    'Parker',
    'Mario',
    'Sofia',
    'Maria',
    'Lucia',
    'Liam',
    'Elijah',
    'Philippe',
    'Rémi',
    'Louka',
    'Mia',
    'Yasmine',
    'Eve',
    'Lea',
    'Chloe',
    'Mark',
    'Nathan',
    'Clara',
    'Cambrie',
    'Janet',
    'Pam',
    'Leslie'
]

last_names = [
    'Mata',
    'Villa',
    'Rossi',
    'Acosta',
    'Schneider',
    'Johnson',
    'Weber',
    'White',
    'Rooney',
    'Reyes',
    'Moretti',
    'Shaffer',
    'Osden',
    'Sokolov',
    'Brown',
    'Fry',
    'Rojas',
    'Chen',
    'Peeters',
    'Santos',
    'Pham',
    'Smith',
    'Wilson',
    'Hernandez',
    'Young',
    'Walker',
    'Okeke',
    'Amari',
    'Sanchez',
    'Turner',
    'Evans',
    'Said',
    'Price',
    'King',
    'Popov',
    'Silva',
    'Cruz',
    'Mills',
    'Warren',
    'Herrera',
    'Jacobs',
    'Munoz',
    'Pogba',
    'Honda',
    'Holt',
    'Li',
    'Morales',
    'York',
    'Davidson',
    'Tremblay',
    'Cote',
    'Diaz',
    'Belanger',
    'Lavoie',
    'Thibault',
    'Demers',
    'Yan',
    'Wei',
    'Lee',
    'Swanson',
    'Collins',
    "O'Shea",
    'Sterling',
    'Bolt'
]
