
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-13T22:15:10-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8b299678f7f1059fab191b5f8d91fa34836a4b3",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
