# coding: utf-8

"""
    RadioManager

    RadioManager

    OpenAPI spec version: 2.0
    Contact: support@pluxbox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import radiomanager_sdk
from radiomanager_sdk.rest import ApiException
from radiomanager_sdk.apis.contact_api import ContactApi


class TestContactApi(unittest.TestCase):
    """ ContactApi unit test stubs """

    def setUp(self):
        self.api = radiomanager_sdk.apis.contact_api.ContactApi()

    def tearDown(self):
        pass

    def test_create_contact(self):
        """
        Test case for create_contact

        Create contact.
        """
        pass

    def test_delete_contact_by_id(self):
        """
        Test case for delete_contact_by_id

        Delete contact by id
        """
        pass

    def test_get_contact_by_id(self):
        """
        Test case for get_contact_by_id

        Get contact by id
        """
        pass

    def test_list_contacts(self):
        """
        Test case for list_contacts

        Get all contacts.
        """
        pass

    def test_update_contact_by_id(self):
        """
        Test case for update_contact_by_id

        Update contact by id
        """
        pass


if __name__ == '__main__':
    unittest.main()
