
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-07T22:24:24-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e990cc7b6b4bdaa29e5bbc72fd1b51f508e1be7",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
