language: python
python:
  - "3.6"
# Apply only on main branches
branches:
  except:
       - /^feat.*$/

# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip python-numpy python-pandas
  - pip install python-coveralls coverage

# command to install emg_analyzer
install:
  - pip install -e .

# test emg_analyzer
script:
  - coverage run --source=emg_analyzer tests/run_tests.py -vv
  - coverage report

after_success:
  - coveralls