image: python:3.6
before_script:
  - pip install tox
stages:
  - style
  - test
  - deploy

py34:
  image: python:3.4
  stage: test
  script:
    - tox -e py34

py35:
  image: python:3.5
  stage: test
  script:
    - tox -e py35

py36:
  stage: test
  script:
    - tox -e py36
  after_script:
    - pip install codecov
    - codecov

flake8:
  stage: style
  script:
    - tox -e flake8

pypi:
  stage: deploy
  script:
    - pip install twine wheel
    - python setup.py sdist bdist_wheel
    - twine upload --config-file .pypirc -u $PYPI_USER -p $PYPI_PASSWORD dist/*
  only:
    - tags
