
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "66ef54c5a979b0c7ac0ecae514103422d0610580",
 "version": "1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
