dist: trusty
sudo: false
language: python

python:
- 3.4
- &latest_py3 3.6

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: bideWwWGyNe/GNb8S1Rv4GfjaupvlgTIpuzmHwyyUI5x/RTdBsejIm0Kj76jtE/HLyLQFkcaXgF5fzs8O2SNgBpfN1LSJ5ryJ6hSFxhlMzdhyp9KOZYbrnvbCqCaTG5xju5vKp/O1E8TSUpH0M/e2zgRKTLqwGVNUBCzKknHKSIpsHYNELZM6ubgyDbL/nYRIwaoq/zO8O5i9qjApfBfkvqYZDRvPw/cl2e7a3use686P+14mJMzbvKtQNl3RUkLmAo6chzDdVsXORXU81Kkug2OIvw8InLlVqC+RlcwK9NrFviMkV9VFu6QxHgiGFc9t1qggZ6I9j4zxlGoucNUOaTjxcDdQjtu2Quu3xkDWI6k5da9+J3lNd9SCca7gRUoD5Qxro6yM1qDrPHyyyBwp6dgIbCFcJogpecD4htnOqcntoZ+tZG3CXWDkMeeHeS0whJ2qFDt3wPLFvQtAl289ow7t/fgCv5lp40LJt0WutH7kkL5ssKqfd7pCAEihq3+S21xMReD9l8ADJnqsFT1FbloqUvs/5mw9oPtjCDKDCpIHYNhRBlDZpG7DHzq2zrt+Vh1SL/ZJICrXAJYmbH6MlT3wTggq1kOax8l/GGhvWiyaIRjXaWOVxoJq8kuVZlM6Yz38GIqd/ZYkXKPa/VOIPjE1EYS3twVojbNxt+YklM=
      distributions: dists
      skip_cleanup: true
      skip_upload_docs: true

cache: pip

install:
- pip install tox

script: tox
