- project:
    name: openstack/keystoneauth
    templates:
      - openstacksdk-functional-tips
      - openstacksdk-tox-tips
      - osc-tox-unit-tips
      - shade-functional-tips
      - shade-tox-tips
