
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-01T11:02:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4033c1ae765f6b60525518f7b3c526b9a68c8de",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
