
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-08T13:31:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ec8f32e791c943a73edc86091d8e3d77fc3949a",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
