routes:
  - name: Google Ads
    routes:
      - www.googleadservices.com/pagead/*
      - adservice.google.com/*
      - "*.googlesyndication.com/pagead/*"

  - name: DoubleClick
    routes:
      - stats.g.doubleclick.net/r/collect
      - cm.g.doubleclick.net/pixel
      - googleads.g.doubleclick.net/*
      - static.doubleclick.net/*
      - ad.doubleclick.net/*

  - name: Google Ads (GoogleTag)
    routes:
      - securepubads.g.doubleclick.net/*
      - www.googletagservices.com/tag/*
    file: doubleclick-pubads.js

  - name: ActiveCampaign
    route: trackcmp.net/visit

  - name: MarkMonitor
    routes:
      - beacon.krxd.net/*
      - cdn.krxd.net/controltag
      - cdn.krxd.net/userdata/*
      - s0.2mdn.net/*

  - name: Gigya
    route: cdns.gigya.com/js/gigya.js
    file: gigya.js

  - name: Google Tag Manager
    route: www.googletagmanager.com/gtm.js
    file: gtm.js

  - name: Zopim Chat
    route: "*.zopim.com/"
    file: zopim.js

  - name: Tealium
    route: tags.tiqcdn.com/utag/*
    file: utag.js

  - name: Visual Web Optimizer
    route: dev.visualwebsiteoptimizer.com/j.php
    file: vwo.js

  - name: Optimizely
    route: cdn.optimizely.com/js/*
    file: optimizely.js

  - name: Scorecard Research
    route: sb.scorecardresearch.com/*

  - name: Chartbeat
    routes:
      - static.chartbeat.com/js/*
      - ping.chartbeat.net/ping

  - name: YieldPro/Ancora
    routes:
      - adserving.ancoraplatform.com/*
      - creatives.ancoraplatform.com/*

  - name: JWPlayer
    route: jwpltx.com/*

  - name: Marktplaats
    route: p.marktplaats.net/*

  - name: Google Adsense
    route: www.google.com/adsense/*
    file: adsense.js

  - name: Google Audiences
    route: www.google.com/ads/ga-audiences

  - name: Google Analytics
    route: www.google-analytics.com/analytics.js
    file: analytics.js

  - name: Google Analytics Plugins
    route: www.google-analytics.com/plugins/*

  - name: Google Analytics Measurements
    route: www.google-analytics.com/collect

  - name: YouTube Event Logger
    routes:
      - www.youtube.com/youtubei/v1/log_event
      - www.youtube.com/youtubei/v1/log_interaction
    file: youtube-log-event.json

  - name: YouTube Stats Beacon
    route: www.youtube.com/api/stats/*

  - name: NewRelic
    route: js-agent.newrelic.com/*

  - name: Index Exchange Marketing
    routes:
      - js-sec.indexww.com/*
      - as-sec.casalemedia.com/*

  - name: ArcPublishing
    route: cdn-api.arcpublishing.com/*

  - name: TrustX Advertisement
    route: sofia.trustx.org/*

  - name: Amazon Adsystem
    route: "*.amazon-adsystem.com/*"

  - name: EffectiveMeasure
    routes:
      - "*.effectivemeasure.net/em.js"
      - "*.effectivemeasure.net/html/*"

  - name: Outbrain
    routes:
      - amplifypixel.outbrain.com/pixel
      - widgets.outbrain.com/external/*

  - name: WpDigital
    route: "*.wpdigital.net/metrics*"

  - name: Twitter Analytics
    routes:
      - analytics.twitter.com/*
      - syndication.twitter.com/*

  - name: Hotjar
    route: static.hotjar.com/*
    file: hotjar.js

  - name: Hotjar Block
    route: vars.hotjar.com/*

  - name: Usabila
    route: w.usabilla.com/*

  - name: AdTech
    routes:
      - aka-cdn.adtech.de/*
      - adserver.adtech.de/*

  - name: Google Interactive Media Ads
    route: imasdk.googleapis.com/*

  - name: AppNexus
    route: "*.adnxs.com/*"

  - name: Gravity R&D
    route: "*.gravityrd-services.com/*"

  - name: Blendle
    route: events.blendle.com/*

  - name: Persgroep Statistics
    route: stats.persgroep.nl/*

  - name: Browserupdate
    route: browser-update.org/update.min.js

  - name: TypeKit tracker
    route: p.typekit.net/p.gif

  - name: Facebook
    routes:
      - www.facebook.com/plugins/like.php
      - www.facebook.com/plugins/likebox.php
      - www.facebook.com/plugins/page.php
      - connect.facebook.net/*
      - www.facebook.com/tr

  - name: MSN Pixels
    route: "*.msn.com/c.gif"

  - name: Akamai Beacon
    route: "*.akstat.io/*"

  - name: ING Monitor
    route: mon.ingbank.nl/*

  - name: Tucows
    routes:
      - t.svtrd.com/*
      - tdn.r42tag.com/*

  - name: Vimeo Player Stats
    route: "*.vimeocdn.com/add/player-stats"

  - name: ABTasty (A/B testing)
    route: try.abtasty.com/*

  - name: BlueConic
    route: cdn.blueconic.net/*

  - name: Lotame (CrowdControl)
    route: tags.crwdcntrl.net/*

  - name: Sizmek Advertising Server
    route: "*.serving-sys.com/serving/*"

  - name: Booking.com Tracking
    routes:
      - www.booking.com/js_tracking
      - www.booking.com/navigation_times
      - cexp.booking.com/*
      - q-ak.bstatic.com/speedtest.png

  - name: GroupeSeb International Development
    route: receiver.analytics.groupe-seb.com/events/*

  - name: TagCommander/Commanders ACT
    route: cdn.tagcommander.com/*

  - name: AddToAny
    route: static.addtoany.com/*

  - name: Twitter
    route: platform.twitter.com/widgets.js

  - name: Google+ PlusOne
    route: apis.google.com/js/plusone.js

  - name: OneSignal Push Notifications
    route: cdn.onesignal.com/sdks/OneSignalSDK.js
    file: one-signal-sdk.js

  - name: Atlassian Analytics
    route: analytics.atlassian.com/analytics/events

  - name: Atlassian Cloud Analytics
    route: "*.atlassian.net/rest/analytics/*"

  - name: Google CDN Logging
    route: csi.gstatic.com/*

  - name: InterYield
    route: www.ti553.com/*

  - name: Bebi Media Beacon
    routes:
      - trck.bebi.com/*
      - st.bebi.com/*

  - name: Unknown Trackers
    routes:
      - "*.2mdnsys.com/*"
      - 178.175.132.130/script/*

  - name: AdForm Pixel
    route: adx.adform.net/*

  - name: Kisscartoon Ads
    route: ad.kisscartoon.es/*

  - name: OnClick Propeller Ads Media
    route: onclkds.com/*

  - name: Statuspage.io UA
    route: ua.statuspage.io/*

  - name: Bol.com Tracker
    routes:
      - swa.bol.com/*
      - cspreport.bol.com/*
      - "*.bltg.s-bol.com/*"

  - name: Mpulse
    route: "*.go-mpulse.net/*"

  - name: Roblox
    route: ecsv2.roblox.com/www/e.png

  - name: Quantcast Measurement Service
    route: secure.quantserve.com/quant.js

  - name: Stackoverflow Timeout
    route: clc.stackoverflow.com/timeout.gif

  - name: AddThis
    routes:
      - "*.addthis.com/js/*"
      - m.addthis.com/live/*
      - m.addthisedge.com/live/*


