name: pygeogrids
channels:
  - conda-forge
  - defaults
dependencies:
- gdal=2.1.0
- geos=3.5.0
- geotiff=1.4.1
- hdf4=4.2.12=1
- hdf5=1.8.17=2
- jbig=2.1
- kealib=1.4.6
- libnetcdf=4.4.1
- libgdal=2.1.0
- mkl=11.3.3=0
- netcdf4=1.2.4
- numpy=1.11.0
- proj4=4.9.2
- pyproj=1.9
- pytest=2.9.1
- pykdtree==1.1.1
