# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20180117_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booksalescount',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
