# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_appliances'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='netbios_name',
            field=models.CharField(default='WIN', max_length=200),
        ),
        migrations.AddField(
            model_name='appliances',
            name='os_type',
            field=models.CharField(default='win32', max_length=200),
        ),
    ]
