---
- name: "Get the resource name"
  set_fact:
    resource_name: "{{ res_def['res_name'] | default(res_def['name']) }}"

- name: "Assign dummy name using uhash value"
  set_fact:
    dummy_name: "{{ resource_name + '-' + uhash }}"

- name: "Teardown dummy resources by looping on count"
  dummy:
    state: absent
    name: "{{ dummy_name }}"
    count: "{{ res_def['count'] | default(1) }}"
  register: outputitem

- name: "set tmp var"
  set_fact:
    tmp: ["{{ outputitem }}"]

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_dummy: "{{ topology_outputs_dummy + tmp }}"

