services:
  - docker

image: lazka/pygobject:latest

.defaults: &defaults
  variables:
    PYTHON: "$CI_JOB_NAME"
  script:
   - bash -x ./.gitlab-ci/test-docker.sh

python2.7:
  <<: *defaults

python3.4:
  <<: *defaults

python3.5:
  <<: *defaults

python3.6:
  <<: *defaults
