
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2018-01-16T17:17:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f790a31930060d3ec251bd6bc0936d921f29872d",
 "version": "0.4.3.post.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
