
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-22T16:11:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "daadb7dec1df2612eaeaf26254eb054dd23f32c1",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
