# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filtering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamfilter',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Internal Counter'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='counter_threshold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Internal Counter Threshold'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='engine_iterations',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Engine Iterations (Max)'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='engine_meta_iterations',
            field=models.SmallIntegerField(default=1, verbose_name='Engine Meta Iterations'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='engine_object',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True, verbose_name='Engine Object'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='engine_object_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Engine Object Timestamp'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='labels_column',
            field=models.CharField(blank=True, help_text='Format: app_label.model.attribute', max_length=100, null=True, verbose_name="Labels' Column"),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='results_storage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Results Storage'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='sl_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Classification'), (1, 'Regression')], default=0, null=True, verbose_name='Supervised Learning Type'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='sm_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'General'), (1, 'Classification'), (2, 'Regression')], default=0, null=True, verbose_name='Statistical Technique Type'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='threshold_actions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Threshold actions'),
        ),
    ]
