# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filtering', '0006_spamfilter_has_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamfilter',
            name='pretraining',
            field=models.CharField(blank=True, help_text='Django Model containing the pre-training dataset in the"app_label.model" format, i.e. "examples.SFPTEnron"', max_length=100, null=True, verbose_name='Pre-Training dataset'),
        ),
        migrations.AlterField(
            model_name='spamfilter',
            name='sm_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'General / System'), (1, 'Classification'), (2, 'Regression')], default=0, null=True, verbose_name='Statistical Technique Type'),
        ),
    ]
