# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filtering', '0008_spamfilter_bow_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamfilter',
            name='is_inferred',
            field=models.BooleanField(default=False, verbose_name='Is Inferred?'),
        ),
        migrations.AlterField(
            model_name='spamfilter',
            name='bow_use_tf_idf',
            field=models.BooleanField(default=True, help_text='Use the TF-IDF transformation?', verbose_name='BoW Use TF-IDF transformation?'),
        ),
    ]
