heat_template_version: queens

description: >
  OpenStack containerized Neutron API service

outputs:
  config_settings:
    description: Extra hieradata needed to log to stdout.
    value:
      neutron::logging::log_dir: ''
  docker_config:
    description: Extra containers needed for logging to stdout or a sidecar container.
    value:
      step_2: {}
  volumes:
    description: The volumes needed to log to stdout or a sidecar container.
    value: null
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value: null
