__version__ = "0.1.16"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.1.16)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '7d361950e2e69288d75d3b17a518b62ed9b25f77'
__git_head_subject__ = u'Finished Release v0.1.16'
__git_head_message__ = u''
__git_dirty_diff__ = u''