# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervised_learning', '0005_svc_has_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svc',
            name='sm_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'General / System'), (1, 'Classification'), (2, 'Regression')], default=0, null=True, verbose_name='Statistical Technique Type'),
        ),
    ]
