language: python

jobs:
  include:
    - python: 3.6
      env: TOXENV=py,codecov
    - python: 3.5
      env: TOXENV=py,codecov
    - python: 3.4
      env: TOXENV=py,codecov
    - python: 2.7
      env: TOXENV=py,codecov
    - python: pypy
      env: TOXENV=py,codecov
    - python: nightly
      env: TOXENV=py

    - stage: deploy
      python: 3.6
      script: .ci/travis-release.sh
      env:
        # TWINE_PASSWORD:
        secure: aFWi+nLxBYHdb0KzZe3L51OqsDbOa5vdNGiz5jD0z0cykly5GnjsIUb4mO1qbFfUufmkDY0y1jLa+41Pk9GUhBdkRYK+a+s0WmfDl6Ns4mZyM3RKQ0fV0nEWK+XxDFeW0kbDC0hKrFO5VIoba9Vi2kM2T7x+Wk6s9Se4EPFajJM4K/PziiWGM3U59FVh56aHJ/2Jqe2xkXDH70bXvNhv4JmkiOHDFfIzBOryZyoIsBJkAA02WvhDk5KiMmlapoDHZdtXoAXijuAM48IQNc7+FlcxcrwzHPKXLeLrkFK1KpZ3vUv6+EbtwjkmSir/wtADv5Fd3k5ita1MO1Drpw9FzZt3AXOv/0Idnt3Wa7jNk0K3/6eRP2Ug+KesZwU19Lccub+gGKlO5wJylWn6m+gU8ZH89rCW0rICk1mIy7jYNO5jZ+ZHXxs/CoiJ98omlx3aCEcf+qLRmUX1vNEziL7S5eWJKDnSH+OoPd0f0B1G8uKOKuvRubn8bKsVN89ALD84FvagyITV7oks7hMy0rDhAauMF7XwU7XMDNCWlNToYKQzfAxVd8Ya0U+IW/MssXcCEci7+6ksrb8QYp1SiUGuFSerPchYRzkWSn4xXKM+SnncqdLZwh89D6yBfw4y06pZRJqktPFtsIkBrprZIYvCzOnWP2Wn37OhCkQ/rfr6nZM=
  allow_failures:
    - python: nightly

stages:
  - test
  - name: deploy
    if: tag IS present

install:
  - pip install tox

script:
  - tox

cache:
  - pip
