image: Visual Studio 2017
build: off  # Not a C# project
environment:
  matrix:
    - TOXENV: py27,codecov
    - TOXENV: py34,codecov
    - TOXENV: py35,codecov
    - TOXENV: py36,codecov

matrix:
  fast_finish: true

install:
  - C:\Python36\python -m pip install --pre -U tox

test_script:
  - C:\Python36\scripts\tox

cache:
  - '%LOCALAPPDATA%\pip\cache'
