
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-09T00:09:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd7e41bf24aed71c16dd47773586c7e86018b52c",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
