MC2P_PAYMENT_DONE = 'D'
MC2P_PAYMENT_CANCELLED = 'C'
MC2P_PAYMENT_EXPIRED = 'E'
MC2P_PAYMENT_PENDING = 'N'

MC2P_SUBSCRIPTION_WAIT = 'W'
MC2P_SUBSCRIPTION_ACTIVE = 'A'
MC2P_SUBSCRIPTION_PAUSED = 'P'
MC2P_SUBSCRIPTION_STOPPED = 'S'

MC2P_AUTHORIZATION_ACTIVE = 'A'
MC2P_AUTHORIZATION_REMOVED = 'R'

MC2P_TYPE_TRANSACTION = 'P'
MC2P_TYPE_SUBSCRIPTION = 'S'
MC2P_TYPE_AUTHORIZATION = 'A'
