sudo: required
dist: trusty
services: docker
language: cpp
python:
- '3.4'
cache:
  timeout: 600

cache:
  - pip
  - apt

addons:
  apt:
    packages:
    - git
    - python3
    - python3-pip

########################
########################
jobs:
  include:
  ######################## XENIAL - TESTS
  - stage: build+test
    os: linux
    env:
    - CMAKE_ARGS='-DBUILD_TESTS=ON'
    - TEST='TRUE'
    - CC_VER="5"
    - PLATFORM='xenial'
    script: "./travis/build.sh"

  ######################## XENIAL - Python
  - stage: build+test
    os: linux
    env:
    - CMAKE_ARGS='-DBUILD_PYTHON=ON'
    - TEST='TRUE'
    - CC_VER="5"
    - PLATFORM='xenial'
    script: "./travis/build.sh"

#  ######################## XENIAL-EMSCRIPTEN
#  - stage: build+test
#    os: linux
#    env:
#    - PLATFORM='xenial-emscripten'
#    script: "./travis/build.sh"
#
#  ######################## OSX + TESTS
#  - stage: build+test
#    os: osx
#    if: branch = master
#    env:
#    - CMAKE_ARGS='-DBUILD_TESTS=ON'
#    - TEST='TRUE'
#    script:
#    - "./travis/build.sh"
#
#  ######################## OSX
#  - stage: build+test
#    os: osx
#    osx_image: xcode9.1
#    if: branch = master
#    env:
#    - CMAKE_ARGS='-DBUILD_PYTHON=ON'
#    script:
#    - "./travis/build.sh"
#
#  ########################
#  - stage: test_deployment
#    script: echo "TODO..."

  ########################
  - stage: publish
    if: tag =~ ^v
    os: linux
    env:
    - CC_VER="5"
    - PLATFORM='xenial'
    - DEPLOY='TRUE'
    script:
    - sudo pip3 install -U pip setuptools twine
    - "./travis/build.sh"

    deploy:
      provider: pypi
      skip_cleanup: true
      user: deployqrl
      password:
        secure: bZxMw6W3WxarfdTR8tvzc4tv5u92IHqP6mw2b0Qm2u3QrHfFr7ZPspedlFHBGF9sx8Lpprn6eeonodBfAEFTZiaQ+JwsLUFyMpIdMnkALWXukIp1LYv1Paj6hqhGYv/sBE2kvsAVzxJRCiIGFc5wnboIxztI4XsnF/OqblVO8DFYTsSlNrIDmwX+Nk5ltL32yOCrsOL0koGt2IDCDUTy848LT4GdL+xOLEW1Pq4R0nFJ0lBN/qOCZHN9wj6+VQGPfiYP0ePzedeAPtYhOXfaJUSnLYYamIqpL2g3X1Q93RKpq+epUDDp7hMT2avF3fV+x9ArW3k4/GKld/vndP+VOmMVyEL1Kj6F7fFzm4dnh7yyf0+DweUSQNiYdJtclyX9yZwKrM3kDSg4PpQ8eMOf8IqVFo75hbx51T072tPE06kir/VUyJ1t3Y8fJZroIIq6ayYPuosf56k2/+T0RrFKSyTeVf9vG+mPM7azQHuU77MOqR7tW7caxbTTuSIpgmYqW7nAggCVJqELoNAQeJfz9tVeLEsn2jLo1CsJikkCQIWXn6JXT+NGslGY5MQTxeEd9+2A7qmsxXs9ZXlkhNSAqlSaMzO5Ao0AdniAiEc3YKoHgPPs9LfB1mXdc3Bl6fToWMd23AmLCIm37TuyCOTs/qf2m/CSqX3bj/a12NOoMu4=
      on:
        tags: true
        all_branches: true

#  ########################
#  - stage: publish
#    if: tag =~ ^v
#    os: linux
#    env:
#    - PLATFORM='xenial-emscripten'
#    script:
#    - "./travis/build.sh"
#    - "./travis/patch_npmversion.sh"
#
#    before_deploy: npm version
#
#    deploy:
#      provider: npm
#      skip_cleanup: true
#      email: "info@theqrl.org"
#      api_key: $NPM_API_KEY
#      on:
#        tags: true
#        all_branches: true
