# Autogenerated by Astropy's setup.py on 2018-01-26 01:10:09
from __future__ import unicode_literals
import datetime

version = "3.0rc2"
githash = "525b95febac57df51506b97267e848f254db8d05"


major = 3
minor = 0
bugfix = 0

release = True
timestamp = datetime.datetime(2018, 1, 26, 1, 10, 9)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
