# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
