# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_catalog', '0027_auto_20170927_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='meta_text',
            field=models.TextField(blank=True, verbose_name='Meta text'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Page title'),
        ),
    ]
