# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_catalog', '0036_migrate_translatable_fields_to_producttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Product type', 'verbose_name_plural': 'Product types'},
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='meta_text',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='title',
        ),
    ]
