# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_catalog', '0037_remove_untranslated_fields_from_producttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttypetranslation',
            old_name='meta_description_t',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='producttypetranslation',
            old_name='meta_keywords_t',
            new_name='meta_keywords',
        ),
        migrations.RenameField(
            model_name='producttypetranslation',
            old_name='meta_text_t',
            new_name='meta_text',
        ),
        migrations.RenameField(
            model_name='producttypetranslation',
            old_name='page_title_t',
            new_name='page_title',
        ),
        migrations.RenameField(
            model_name='producttypetranslation',
            old_name='title_t',
            new_name='title',
        ),
    ]
