# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_catalog', '0045_remove_untranslated_fields_from_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendortranslation',
            old_name='description_t',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vendortranslation',
            old_name='title_t',
            new_name='title',
        ),
    ]
