# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_catalog', '0048_migrate_translatable_fields_for_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='meta_text',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='title',
        ),
    ]
