# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_catalog', '0050_remove_untranslated_fields_from_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title_t', models.CharField(max_length=255, verbose_name='Title')),
                ('description_t', models.TextField(blank=True, verbose_name='Description')),
                ('page_title', models.CharField(blank=True, max_length=255, verbose_name='Page title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta keywords')),
                ('meta_text', models.TextField(blank=True, verbose_name='Meta text')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pcart_catalog.Product')),
            ],
            options={
                'managed': True,
                'db_tablespace': '',
                'default_permissions': (),
                'db_table': 'pcart_catalog_product_translation',
                'verbose_name': 'Product Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
