# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_catalog', '0057_migrate_translatable_fields_for_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='title',
        ),
    ]
