# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_catalog', '0062_remove_untranslated_fields_from_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimagetranslation',
            old_name='title_t',
            new_name='title',
        ),
    ]
