# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-04 10:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_catalog', '0076_collection_small_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='properties_filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), blank=True, default=list, help_text='Comma separated list of properties labels in proper order which you want to include to filters. Leave this field blank if you want to show all filters.', size=None, verbose_name='Properties filters'),
        ),
    ]
