sudo: false
language: python
env:
  - USE_LXML=true
  - USE_LXML=false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - if $USE_LXML; then pip install lxml; fi
install: python setup.py build
script: python setup.py test
