# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_novaposhta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Description (uk)')),
                ('description_ru', models.CharField(max_length=255, verbose_name='Description (ru)')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='pcart_novaposhta.Area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.RemoveField(
            model_name='office',
            name='city_description',
        ),
        migrations.RemoveField(
            model_name='office',
            name='city_description_ru',
        ),
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='pcart_novaposhta.City', verbose_name='City'),
            preserve_default=False,
        ),
    ]
