# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_novaposhta', '0003_auto_20170306_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('description',), 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('description',), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ('number',), 'verbose_name': 'Office', 'verbose_name_plural': 'Offices'},
        ),
        migrations.AlterField(
            model_name='office',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='office',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
