
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-06T18:37:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8d5367c7cb06f37f4a8e9f629001520ebe09766",
 "version": "0.11.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
