# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mc2p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc2pconfig',
            name='key',
            field=models.CharField(max_length=32, verbose_name='Key'),
        ),
    ]