
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-23T15:22:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec32a002d998cef77559b777b890e4e26579c539",
 "version": "0.1.80"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
