
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-14T11:39:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "af4dcb325d70629435456ce253275edbb84877e1",
 "version": "0.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
