
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-08T12:02:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "99dcd6fe192746a84ec5dbd8944b84251f26f152",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
