
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d9d691af2b176824fab2dd75d375d9f508172e07",
 "version": "v0.1.1-alpha.post.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
