package:
  name: xnd
  version: 0.2.0b2

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY', 'NA') }}_{{ environ.get('GIT_BUILD_STR', 'NA') }}

test:
  files:
    - test
  commands:
    - python test/test_xnd.py --long
  requires:
    - libndtypes ==0.2.0b2
    - libxnd ==0.2.0b2
    - ndtypes ==0.2.0b2

requirements:
  build:
    - libndtypes ==0.2.0b2
    - libxnd ==0.2.0b2
    - ndtypes ==0.2.0b2
  run:
    - libndtypes ==0.2.0b2
    - libxnd ==0.2.0b2
    - ndtypes ==0.2.0b2

about:
  home: https://github.com/plures/
  license: BSD 3-clause

source:
  git_url: ../../
