
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-17T12:32:56-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9c25433b85661728e0bf60bef2dfecc4db7bfba",
 "version": "3.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
