- project:
    name: openstack/ironic-inspector
    check:
      jobs:
        - ironic-inspector-tempest-dsvm-discovery
        - ironic-inspector-tox-func
        - ironic-inspector-tox-func3
        - ironic-tempest-dsvm-ironic-inspector
    gate:
      jobs:
        - ironic-inspector-tempest-dsvm-discovery
        - ironic-inspector-tox-func
        - ironic-inspector-tox-func3
        - ironic-tempest-dsvm-ironic-inspector
