language: python
sudo: false
cache:
- pip
python:
- '3.5'
- '3.6'
- 'nightly'
matrix:
  fast_finish: true
  allow_failures:
  - python: 'nightly'
install:
- pip install -U codecov
script:
- coverage run --source ssdp -m pytest tests
after_success:
- codecov
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: aFTQloJGfJprEP0S+oDBPhdsVdzyIM5H7pc6lRzO6QU1gxmsZdlyR7OR4NACUFW1+xhCLYI4ic1cJj9+0cBW6Iq/kjQkdFw/6pRw47rQFn82dwKXVVqkylw0hhcrvuHgwog9gtt6cZOPi0mTEx3/ALt4jYAJydYfzkWU6ZTwCjZbjOqJ5ETCDsckw6L58MLnKf+wkLXztt8ET3dPgNodJzVzbMPnaYVjk+2laTru7Yqz4jWTFmyTiCAzTQL+e+Bl2atomApIG4totlayzLjZ87ro9kQ+kUhuhAPFeAO+eEVDPO3jJrNRAa2e7rTx8mA7qQulcB/VcP/BWq1LR8oha7D9eGaRLKEmlcudEsCyTBoAEkhU2VOxsJVncoJkc7/+vxXrwEBGg7rx9HrbqVJMVwsgAMlHUigFuNgJlcFbd9xwkymb+672Ui/fTrTlYFpJJYUphsx5dXV4YMAXgy5TE0VTm+d1e3khDI3tisl252uRl7jcgUJTxRR0kXZ7D1vPaDMLo9z9G0XrAt25bEscRwfotSPcjqIxB3g4aXb/HwT+iN2qQEkET+x2iBpBpI/uKuars7U66WAlTN/E/JvOrcXmm2zpNDpSvoclN5RMND1/yEGPoh+a14E/UkAdiYajDzDu7WPZKEHjBVfuScGfmfhVlLjtx+aUW26Oo7s8LQM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: codingjoe/ssdp
