- hosts: all
  name: Autoconverted job legacy-senlin-dsvm-tempest-py35-api from old job gate-senlin-dsvm-tempest-py35-api-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x

          export PYTHONUNBUFFERED=True
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST=1
          export KEEP_LOCALRC=1
          export DEVSTACK_GATE_TEMPEST_NOTESTS=1
          export DEVSTACK_GATE_EXERCISES=0
          export DEVSTACK_GATE_INSTALL_TESTONLY=1

          if [ "py35" == "py35" ]; then
            export DEVSTACK_GATE_USE_PYTHON3=True
          else
            export DEVSTACK_GATE_USE_PYTHON3=False
          fi

          export SENLIN_TEST_TYPE="api"
          export DEVSTACK_GATE_TEMPEST_REGEX="senlin_tempest_plugin.tests.${SENLIN_TEST_TYPE}"

          services=rabbit,mysql,dstat,key,tempest
          services+=,g-api,g-reg
          services+=,n-api,n-cpu,n-cond,n-sch,n-crt
          # placement services mandatory for nova from ocata
          if [[ "stable/newton" != $ZUUL_BRANCH ]]; then
             services+=,placement-api,placement-client
          fi
          services+=,c-sch,c-api,c-vol,c-bak
          services+=,q-svc,q-dhcp,q-meta,q-agt,q-l3

          export PROJECTS="openstack/senlin $PROJECTS"
          export DEVSTACK_LOCAL_CONFIG="enable_plugin senlin https://git.openstack.org/openstack/senlin"

          if [ "${SENLIN_TEST_TYPE}" == "api" ]||[ "${SENLIN_TEST_TYPE}" == "functional" ]; then
            export SENLIN_BACKEND="openstack_test"
          else
            export SENLIN_BACKEND="openstack"
            export PROJECTS="openstack/heat $PROJECTS"
            export DEVSTACK_LOCAL_CONFIG+=$'\n'"enable_plugin heat git://git.openstack.org/openstack/heat"

            # Enable LBaaS V2 plugin
            services+=,q-lbaasv2
            export PROJECTS="openstack/neutron-lbaas $PROJECTS"
            export DEVSTACK_LOCAL_CONFIG+=$'\n'"enable_plugin neutron-lbaas https://git.openstack.org/openstack/neutron-lbaas"

            # Enable Zaqar
            export PROJECTS="openstack/zaqar $PROJECTS"
            export PROJECTS="openstack/python-zaqarclient $PROJECTS"
            export PROJECTS="openstack/zaqar-ui $PROJECTS"
            export DEVSTACK_LOCAL_CONFIG+=$'\n'"enable_plugin zaqar git://git.openstack.org/openstack/zaqar"
          fi

          # use senlin-tempest-plugin
          export PROJECTS="openstack/senlin-tempest-plugin $PROJECTS"
          export DEVSTACK_LOCAL_CONFIG+=$'\n'"TEMPEST_PLUGINS+=' /opt/stack/new/senlin-tempest-plugin'"

          export OVERRIDE_ENABLED_SERVICES=$services

          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function pre_test_hook {
              cd /opt/stack/new/senlin/senlin/tests/tempest/
              ./pre_test_hook.sh
          }
          export -f pre_test_hook

          function post_test_hook {
              cd /opt/stack/new/senlin/senlin/tests/tempest/
              ./post_test_hook.sh senlin_tempest_plugin.tests.${SENLIN_TEST_TYPE}
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
