#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['wort']

package_data = \
{'': ['*']}

setup(name='wort',
      version='0.0.1',
      description='A web service for sourmash operations.',
      author='Luiz Irber',
      author_email='wort@luizirber.org',
      url='http://luizirber.org',
      packages=packages,
      package_data=package_data,
     )
