dist: trusty
sudo: false
language: python

python:
- 2.7
- &latest_py3 3.6

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: Pj1WzgrM/Am/iNT3m4dKz5am14FhOmoIoIgeZ+VLeCnjJ9NGxn9ySjuZi2mKRFZohCGoEQDMktLJbCRuafJ+j59QRE/tbGLW3DrGf+4df99AaNhmOdn+22vzPPSu685AyRe3IzCQj2+WbPGb3JXIlIPwL8/tkqoItFNuNutiVyaVjnqjbmVUSCJPt6h97Eqaw3UoWag6aiux6eht437RhsU2GmtNzOyFelXwHaL/Juc9AJtXCe4pQzQU07mtrh5egkq2hz8ni7kqDn4WITmlvgpq7wZjOBGZ8yUK+Dhxj0CxYJuTIiwbKTGgDk+IB2dZoivCwS74VHVD5rWFVtdN5e+H078xy8nWqhZIYWYj9YaCtSDySqCXiM+kugyI1PS+ebHy8d8XQ2SN26WnydhhHh5ENLQv7FHVcise50S2BmhDOV5r14RMeiGKpAiR6mlmaLfbakI9EW8rPaC7mzLHkTh1ZSKpcH/xRjEGJ7L6L6m/HkcOSt1dnEA3b4xHemSk18HQQlwGL1SzDFlnAcGp8nWZ1ZgW3LOVaRjvD8t5B+xVHam43CAd16eAJXubaXWJXuPGfaTiRzBKW8A9baIyoGUDx4ARIcZTIq3rJ9aohRNDvSmAAW+x4qx7MVsQppyrp7e6xng83oDT795WaGMSLZ07A21F25/nG84NnSi5N9M=
      distributions: dists
      skip_cleanup: true
      skip_upload_docs: true

cache: pip

install:
- pip install tox tox-venv

script: tox
