# coding: utf-8

"""
    Fortanix SDKMS REST API

    This is a set of REST APIs for accessing the Fortanix Self-Defending Key Management System. This includes APIs for managing accounts, and for performing cryptographic and key management operations. 

    OpenAPI spec version: 1.0.0-20171218
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import sdkms/v1
from sdkms/v1.rest import ApiException
from sdkms/v1.apis.sign_and_verify_api import SignAndVerifyApi


class TestSignAndVerifyApi(unittest.TestCase):
    """ SignAndVerifyApi unit test stubs """

    def setUp(self):
        self.api = sdkms/v1.apis.sign_and_verify_api.SignAndVerifyApi()

    def tearDown(self):
        pass

    def test_batch_sign(self):
        """
        Test case for batch_sign

        Batch sign with one or more private keys
        """
        pass

    def test_batch_verify(self):
        """
        Test case for batch_verify

        Batch verify with one or more private keys
        """
        pass

    def test_sign(self):
        """
        Test case for sign

        Sign with a private key
        """
        pass

    def test_sign_ex(self):
        """
        Test case for sign_ex

        Sign with a private key
        """
        pass

    def test_verify(self):
        """
        Test case for verify

        Verify a signature with a key
        """
        pass

    def test_verify_ex(self):
        """
        Test case for verify_ex

        Verify a signature with a key
        """
        pass


if __name__ == '__main__':
    unittest.main()
