# coding: utf-8

"""
    Fortanix SDKMS REST API

    This is a set of REST APIs for accessing the Fortanix Self-Defending Key Management System. This includes APIs for managing accounts, and for performing cryptographic and key management operations. 

    OpenAPI spec version: 1.0.0-20171218
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import sdkms/v1
from sdkms/v1.rest import ApiException
from sdkms/v1.models.batch_decrypt_request_inner import BatchDecryptRequestInner


class TestBatchDecryptRequestInner(unittest.TestCase):
    """ BatchDecryptRequestInner unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBatchDecryptRequestInner(self):
        """
        Test BatchDecryptRequestInner
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = sdkms/v1.models.batch_decrypt_request_inner.BatchDecryptRequestInner()
        pass


if __name__ == '__main__':
    unittest.main()
