NUMERICAL_DTYPES = ['float', 'float64', 'int', 'int64']
CATEGORICAL_DTYPES = ['category']
BOOLEAN_DTYPES = ['bool']
DATETIMES_DTYPES = ['datetime64[ns]']
ORDERED_DTYPES = NUMERICAL_DTYPES + CATEGORICAL_DTYPES + DATETIMES_DTYPES
