language: python
python: 2.7
before_install:
  - pip install --upgrade setuptools
install:
    - pip install --upgrade coveralls codecov tox
script: tox -e unit
after_success:
  - coveralls
  - codecov
