# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filtering', '0007_auto_20171213_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamfilter',
            name='bow_is_enabled',
            field=models.BooleanField(default=True, help_text='Enable Bag of Words transformation', verbose_name='BoW Is Enabled?'),
        ),
    ]
