# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filtering', '0009_auto_20171220_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamfilter',
            name='cv_folds',
            field=models.SmallIntegerField(blank=True, help_text='Quantity of Folds to be used in Cross Validation', null=True, verbose_name='Cross Validation Folds'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='cv_is_enabled',
            field=models.BooleanField(default=True, help_text='Enable Cross Validation', verbose_name='Cross Validation is Enabled?'),
        ),
        migrations.AddField(
            model_name='spamfilter',
            name='cv_metric',
            field=models.CharField(blank=True, choices=[('accuracy', 'Accuracy'), ('average_precision', 'Average Precision'), ('f1', 'F1'), ('neg_log_loss', 'Logistic Loss'), ('precision', 'Precision'), ('recall', 'Recall'), ('roc_auc', 'Area under ROC Curve')], help_text='Metric to be evaluated in Cross Validation', max_length=20, null=True, verbose_name='Cross Validation Metric'),
        ),
    ]
