# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 19:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('pcart_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Content')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='pcart_customers.Customer', verbose_name='Customer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name_plural': 'Carts',
                'verbose_name': 'Cart',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('site', 'customer')]),
        ),
    ]
