# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_cart', '0002_order_ordernumberformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Payment data'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Shipping data'),
        ),
    ]
