# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_cart', '0003_auto_20170212_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total price'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_weight',
            field=models.FloatField(default=0.0, verbose_name='Total weight (kg)'),
        ),
    ]
