# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_cart', '0004_auto_20170222_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Weight')),
            ],
            options={
                'ordering': ['weight'],
                'verbose_name': 'Order status',
                'verbose_name_plural': 'Order statuses',
            },
        ),
    ]
