# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pcart_cart.models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_cart', '0005_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=pcart_cart.models.get_default_order_status, on_delete=django.db.models.deletion.CASCADE, to='pcart_cart.OrderStatus', verbose_name='Status'),
        ),
    ]
