# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_cart', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='export_status',
            field=models.CharField(choices=[('notset', 'Not set'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='notset', help_text='Reserved field for integration with third-party software.', max_length=70, verbose_name='Export status'),
        ),
    ]
