
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-23T15:27:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2db3b90292a5b96bd08f39c709e5ccbd59c0c698",
 "version": "2.13.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
