language: python
python:
- '2.7'
- '3.5'
sudo: required
dist: trusty
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O anaconda.sh;
- export python_version=$TRAVIS_PYTHON_VERSION
- bash anaconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda config --add channels http://conda.binstar.org/omnia
- bash scripts/install_deepchem_conda.sh deepchem
- source activate deepchem
- pip install yapf==0.20.0
- pip install coveralls
- python setup.py install
script:
- nosetests --with-flaky -a '!slow' --with-timer --with-coverage --cover-package=deepchem
  -v deepchem --nologcapture
- find ./deepchem | grep .py$ |xargs python -m doctest -v
- bash devtools/travis-ci/test_format_code.sh
after_success:
- echo $TRAVIS_SECURE_ENV_VARS
- coveralls
deploy:
  provider: pypi
  user: "lilleswing"
  password:
    secure: EcOuKUABsp7yUYjCseh9iPltC+sOn/AXh774moIT1InQN8ts04t6E1H1+A4BDlIGptWIaarZKfoa80Hqwtuxu8T6UcoPKLfHwGsmXFMTe5lXZQHopP1zNCgFYNC4ShcXmYqPw5zHSVPoJL1Ub1VbEBK+B+Rph8/YIaogPmZ8B6KpbtgD74dubR29XNMrZKJfbNwnqGX9Mv/X5MXgq26fFm77OV/tJf/O1qeq3id6NbCQ3/cjVnG2/TqNTGThmBWW7n+eA4XImlfSrS4NgiMSOHnU+zXmnr0Trs8CxspaR9pXF50JVAR0Q230ZireJi85maZzE4onC3kGC1knLI2ERVgp4tySfe5XRa/iXz94mmqrZjbLXxDpkQngU1HLhC9ojrAJWq6K3mBzz7xDL5hlB+IzIg8LBz08wEm+U+DLt/ygR6QGASit5NWC0QCbyARxFDfk60VubXR0VSsd+rs3dgrDsvphijZmys6Kt3WeuBYS5uzu9JIjukyVIX/PN2tThV6AQKnTuhcnmqUjfTwm2ueMe5PYIPAHFINk7nugfxpc2EeFO0FbSIJn6+RRdGklZY3ldda1aInyrb3kyoEl2Eyqo8AdmNCSpriI2wSa2r2OL+IH2U9N+e1qof6bKJFel2PetHp7p2l0ihZqQQgxTDU8dro3lTrppL4+H2TOB6M=
