PYSPARK = 'pyspark'
SCIKIT = 'scikit-learn'
PANDAS = 'pandas'
XGBOOST= 'xgboost'
MLPIPELINE = 'mlpipelinepy'
IBMSPARKPIPELINE = 'ibmsparkpipeline'
TENSORFLOW = 'tensorflow'
SPSS_MODELER = 'spss-modeler'

DISPLAY_PYSPARK = 'PySpark'
DISPLAY_SCIKIT = 'scikit-learn'
DISPLAY_PANDAS = 'Pandas'
DISPLAY_XGBOOST = 'XGBoost'
DISPLAY_MLPIPELINE = 'MLPipeline'
DISPLAY_IBMSPARKPIPELINE = 'IBMSparkPipeline'
DISPLAY_TENSORFLOW = 'Tensorflow'