
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e92b82737793d4e050d94f8a9170790e90b77fca",
 "version": "0.4.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
