[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "packageManifest"
author = "Russell Smiley"
author-email = "im.russell.smiley@gmail.com"
home-page = "https://gitlab.com/blueskyjunkie/package-manifest"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
requires = [ "pyyaml" ]
description-file = "README.rst"
keywords = "manifest package distribution file"
requires-python = ">=3"
