
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-18T12:49:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dbfd23504d12ddbc211aac0e78626e6c228afc12",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
