language: python
sudo: required
python:
- '2.7'
- '3.6'
install:
- pip install coveralls
- pip install -r test_requirements.txt
- python setup.py develop
script:
- py.test tests --doctest-modules sshutil
deploy:
  provider: pypi
  user: choppsv1
  password:
    secure: xeIneVrq0p1IkPBnEDp+d2s6Ez3G/4NLCSW/sngpnhiTTifsrqjU4oSvNM+eGDakqc2yy1SjFXelTvTunTWw1BuNqKSexwM6Ly+gqfWenrhEYjWMb0X33pQHqmkLmlCFXO/7eOxTxwl5V4hIv7lxnfs0xdhxft8EyAT/FJ5vM1ssRoHxEA1BXz7baoJ1UHzHXDtSh6qNt96oDu+d7nyqH/AIuRra8Fh4fGUiguH/1QeC73XMSS9pTMOU9VWMhuNMJK/H6Ioi2moI8/VqXyZnY9rwtAnyDNiIOsduNvMj3q1l7Ed+DU9X1zf6FSMkz7XdzTb7vAi6+JGCEhIKfspT8auoOKQmNGe4X3BlhWDnUD7HsoL9HsWHeRLe5Qakm8ryxfPBhw8qmsXBSdU4hCQMqFwtlAQLihN5LyOlynKnp428zxD1KRKp1fUGa4NRXo42+EpY1qRRKZbqCrNngwEv2PCRzxXF1ZqaqYbeKIsossCiES4sWQybFH+jjOUg+1eba6xKbkldefWYNtEA4yIYSeXG2ATYgGx6g5NmdvShFFtmBgdSPt8rWHZAC7euKFUidMkjAe4KDA8MKcsWSK5yS/iO8Lo2SLOxX7mMBFIsNTs1ovWPFdO59znrI6l0FnSfpgCL0k8DdkNcbdTl49CWDHm45Xb0XgEbtdYhDbDSzv8=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
