- project:
    name: openstack/python-designateclient
    templates:
      - designate-devstack-jobs
    check:
      jobs:
        - requirements-check:
            voting: false
    gate:
      jobs:
        - requirements-check:
            voting: false
