
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-09T21:03:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0457426aae5ff6b018b0c83bf985807c62ed1415",
 "version": "0.12.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
