# coding: utf-8

"""
    Tts API

    Description  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import telestream_cloud_tts
from telestream_cloud_tts.models.fragment_variant import FragmentVariant  # noqa: E501
from telestream_cloud_tts.rest import ApiException


class TestFragmentVariant(unittest.TestCase):
    """FragmentVariant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFragmentVariant(self):
        """Test FragmentVariant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = telestream_cloud_tts.models.fragment_variant.FragmentVariant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
