# coding: utf-8

"""
    Tts API

    Description  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import telestream_cloud_tts
from telestream_cloud_tts.api.tts_api import TtsApi  # noqa: E501
from telestream_cloud_tts.rest import ApiException


class TestTtsApi(unittest.TestCase):
    """TtsApi unit test stubs"""

    def setUp(self):
        self.api = telestream_cloud_tts.api.tts_api.TtsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_corpora(self):
        """Test case for corpora

        Returns a collection of Corpora  # noqa: E501
        """
        pass

    def test_corpus(self):
        """Test case for corpus

        Returns the Corpus  # noqa: E501
        """
        pass

    def test_create_corpus(self):
        """Test case for create_corpus

        Creates a new Corpus  # noqa: E501
        """
        pass

    def test_create_job(self):
        """Test case for create_job

        Creates a new Job  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Creates a new Project  # noqa: E501
        """
        pass

    def test_delete_corpus(self):
        """Test case for delete_corpus

        Creates a new Corpus  # noqa: E501
        """
        pass

    def test_delete_job(self):
        """Test case for delete_job

        Deletes the Job  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Deletes the Project  # noqa: E501
        """
        pass

    def test_job(self):
        """Test case for job

        Returns the Job  # noqa: E501
        """
        pass

    def test_job_result(self):
        """Test case for job_result

        Returns the Job Result  # noqa: E501
        """
        pass

    def test_jobs(self):
        """Test case for jobs

        Returns a collection of Jobs  # noqa: E501
        """
        pass

    def test_project(self):
        """Test case for project

        Returns the Project  # noqa: E501
        """
        pass

    def test_projects(self):
        """Test case for projects

        Returns a collection of Projects  # noqa: E501
        """
        pass

    def test_train_project(self):
        """Test case for train_project

        Queues training  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Updates an existing Project  # noqa: E501
        """
        pass

    def test_upload_video(self):
        """Test case for upload_video

        Creates an upload session  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
