import pandas_lite._libs.math as m

funcs = {'i': {0: {'min': m.min_int,
                   'max': m.max_int,
                   'sum': m.sum_int,
                   'mean': m.mean_int,
                   'median': m.median_int,
                   'std': m.std_int,
                   'var': m.var_int,
                   'any': m.any_int,
                   'all': m.all_int,
                   'argmax': m.argmax_int,
                   'argmin': m.argmin_int,
                   'count': m.count_int,
                   'cummin': m.cummin_int,
                   'cummax': m.cummax_int,
                   'cumsum': m.cumsum_int}},

         'b': {0: {'min': m.min_bool,
                   'max': m.max_bool,
                   'sum': m.sum_bool,
                   'mean': m.mean_bool,
                   'median': m.median_bool,
                   'std': m.std_bool,
                   'var': m.var_bool,
                   'any': m.any_bool,
                   'all': m.all_bool,
                   'argmax': m.argmax_bool,
                   'argmin': m.argmin_bool,
                   'count': m.count_bool,
                   'cummin': m.cummin_bool,
                   'cummax': m.cummax_bool,
                   'cumsum': m.cumsum_bool}},

         'f': {0: {'min': m.min_float_nan,
                   'max': m.max_float_nan,
                   'sum': m.sum_float_nan,
                   'mean': m.mean_float_nan,
                   'median': m.median_float_nan,
                   'std': m.std_float_nan,
                   'var': m.var_float_nan,
                   'any': m.any_float,
                   'all': m.all_float,
                   'argmax': m.argmax_float_nan,
                   'argmin': m.argmin_float_nan,
                   'count': m.count_float,
                   'cummin': m.cummin_float_nan,
                   'cummax': m.cummax_float_nan,
                   'cumsum': m.cumsum_float_nan},

               1: {'min': m.min_float,
                   'max': m.max_float,
                   'sum': m.sum_float,
                   'mean': m.mean_float,
                   'median': m.median_float,
                   'std': m.std_float,
                   'var': m.var_float,
                   'any': m.any_float,
                   'all': m.all_float,
                   'argmax': m.argmax_float,
                   'argmin': m.argmin_float,
                   'count': m.count_float,
                   'cummin': m.cummin_float,
                   'cummax': m.cummax_float,
                   'cumsum': m.cumsum_float}},

         'O': {0: {'min': m.min_str_nan,
                   'max': m.max_str_nan,
                   'sum': m.sum_str_nan,
                   'any': m.any_str,
                   'all': m.all_str,
                   'argmax': m.argmax_str_nan,
                   'argmin': m.argmin_str_nan,
                   'count': m.count_str,
                   'cummin': m.cummin_str_nan,
                   'cummax': m.cummax_str_nan,
                   'cumsum': m.cumsum_str_nan},

               1: {'min': m.min_str,
                   'max': m.max_str,
                   'sum': m.sum_str,
                   'any': m.any_str,
                   'all': m.all_str,
                   'argmax': m.argmax_str,
                   'argmin': m.argmin_str,
                   'count': m.count_str,
                   'cummin': m.cummin_str,
                   'cummax': m.cummax_str,
                   'cumsum': m.cumsum_str}}}

funcs['i'][1] = funcs['i'][0]
funcs['b'][1] = funcs['b'][0]

# cumfuncs = {'i': {0: {'cummin': m.cummin_int,
#                       'cummax': m.cummax_int,
#                       'cumsum': m.cumsum_int}},

#             'b': {0: {'cummin': m.cummin_bool,
#                       'cummax': m.cummax_bool,
#                       'cumsum': m.cumsum_bool}},

#             'f': {0: {'cummin': m.cummin_float_nan,
#                       'cummax': m.cummax_float_nan,
#                       'cumsum': m.cumsum_float_nan},

#                   1: {'cummin': m.cummin_float,
#                       'cummax': m.cummax_float,
#                       'cumsum': m.cumsum_float}},

#             'O': {0: {'cummin': m.cummin_str_nan,
#                       'cummax': m.cummax_str_nan,
#                       'cumsum': m.cumsum_str_nan},

#                   1: {'cummin': m.cummin_str,
#                       'cummax': m.cummax_str,
#                       'cumsum': m.cumsum_str}}}
