language: python
python:
 - '3.5'

script: echo "Done"
deploy:
  provider: pypi
  user: danni
  password:
    secure: bZSMxZfYqcqe62cKEGyx7yruPMk46VssYEL8ROkoXCZjnXCVr8HmNHf0rzpIybmiH2FDLX46ip2Ftx0qc6NDszJLxKGnAgURBw8CrEgcooBFjFLKMRFIrR3vUg1eXl18boHoAsW3W/2urpbMEe1hSijZpA7ESRP2oxs/1M0RdBJgm+lhhwjT9xyMm54BJJ/MzuURqS6T7EXQQEs5B4RACAIKqHPVClCu0mSl1XaDzzOXLeZ2S+SmZ+x70pCSBfSyn7Vnn9YhosuS8blEWDjV4eBDXrnaFa3SKRxRx55dtjVomHAdE6sNrMNpzM356g6+92CGBd/xdkeHuualQTTliIl2GcUKEvLgYMZbThsvMhQT3zfRuAZZamexhtTqMho29bHMszzkudEMdkfKZxLi5GzdwNTCD98bz8TDi2yQXiKHOAREI/SE3OU3tZALUiHhVRNXQ1AbggwalZ9j90ALsUBLGoW1yc1XoLeqTgCCqVJZlbhYxrGPnliXtaAzOzvgZ/1Mtuhk2ZKc3jLQ41g2kfKDnxkl+aHrwvq/WlByxHj0RaTtezSUwyjz2A+WOIRqB2UwgpVg8KN5ONAMP17q/DRIRuWt0WvukIjmfM74TUDHbhePoJYsi5nLr/q8a4iUv+Gp/Qy6ECnbZrZTO53ObhJX+3op+VAurbMORQ0H8FU=
  on:
    tags: true
    all_branches: true
    python: 3.5
    condition: '"$TRAVIS_TAG" = "$(python setup.py --version)"'
