
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-06T13:06:34+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea6571d7300bf30747b4f25ac6ba01dbdfd4a757",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
