# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervised_learning', '0003_auto_20171127_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svc',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
