# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervised_learning', '0006_auto_20171213_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='svc',
            name='is_inferred',
            field=models.BooleanField(default=False, verbose_name='Is Inferred?'),
        ),
    ]
