
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b5128731c9d627040ec17a0f1a3ab0ae4588555c",
 "version": "0.4.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
