language: python
python: '2.7'
script: echo "no tests"
deploy:
  provider: pypi
  user: iml
  password:
    secure: ft/srevwOsZ/bRtmyqtv2MJVggjvIfNp7Yf402qdD+tCVzBEWLd3YplHgW0kziI26H4ElR/cTdL0KoLPe0s8SVGb1BZ9GyqG0qjgkotxVwyy4LzlHKwsCuEYSJbOLUbzpcvzcjpEU9PwY+AKeA3DiJsbC7FTrve7fmeS9NZ1+X3tEZL/mmszHUXwo17onHx1057UkOlizLEMwz/cuUnS0klSogF4M/u3PTVxIUdrrG3dDzf4vKPXPLtnxq+vKuysP0YAGDo0podsb7ZZLyV7X6tsRfMkwJJhnYPayr25QLAyWbFjS7hWCpHJ0OQ2S+4bjJFL/3WfBQykRqg423jfI4qjUTgK238VuviY0BGcTLttISLLAufpZVu7UcP26g6WqvPhXog1NIOHFNuZgvG0mwOJhKKwr6k/BEoky/0Ijj3cDW4jyjqj8I9FAm3z7tgnfiYT3eQlIanjxkGVqBKRmDah7GGjG/YNO441zrga9sPJ6LdXfwrX+1qW9OzGDHAMT7LhoGMLz1qPv1ns+STsDRLAn1vkwReawaj4Se1dzwTzm5v3xsQx3dGKqZ3rBlH6UWl7r44VAZ6Z/haLBrXGHvoPFNEdH0L8YnM8eWGBmuvqjnmiAcHK5+FgAQYcjgxZd8efrIJOOG3xMroT7weZbeTTnSGP29Tm0VZL7V12tWc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: intel-hpdd/iml_sos_plugin
