sudo: false
language: python
python:
  - "2.7"
  - "3.5"
env:
  - TWISTED=true
  - TWISTED=false
services:
  - rabbitmq-server
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install unittest2; fi
  - pip install six msgpack-python pika asgiref cffi cryptography asgi_ipc
script:
  - python setup.py develop
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python -m unittest2; else python -m unittest; fi
