# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python:
  - 3.6
  - 3.5

install:
  - pip install -U pip pipenv
  - make dev

script:
  - make check
  - make dists
  - make test

after_success:
  coveralls

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  user: stibbons
  distributions: sdist bdist_wheel
  password:
    secure: jmxqrciBDaJjozAMM+Y56gfJ1h3NdKXEaR5cbfDXAPdkTKsqAormPaugKDfKDja7bHd4o0cMVZLB8SVUwv7rG3VDu9oTHiujr6kiPfx6Zltpma6FRdnvOzYcCf/GHEmAhNIbMvTuoD6U84pAojBCP+Z3daWzWtHatagCUZxP72AA3l9CF8CF8BgzxIcAxHs+tLxjKCjLRdcNOfXBj7FSm8jTOG529IhGaSJgZ0+T8zyKpsE9PvXlxYzsMZMyCqBnyNsU25hGIRERmL2ghWcvhBCiNmLsNT1SgIXZvPEES2+F16e0jojcjIGZwZHHcZfOHUXjZQ18t/OAt8U3hZDoA8saFAproRe38KDlimvmdnN39t0p0eRFEPEix942t49CkLyjbEdEZf40HG8IFEZlydca24o7mTdxjp48F2wObYI1+Xz8+ZkMLvlsAufHYjSiWsbVU6AuThmOjqFpX0SnTEUvGQXNZzDBdEPE9RSVZUrqd0lKIa3AOS8NIlnellVOalSl8XN9OT2LRCrctE66sc69MONBKwEglPGdAKf/FMXxS/DrsskA1dSOg7YALehEvnZG7AwXqJY/dGScb5j5J12mVPQFxZ2kzHAuGuzXa7UPVPx7p+iQqDvYBpmgsoGggLVDYRnqm3bNDeRuRKDlMCMiWhpAAt/UGzjdIFRw5rs=
  on:
    tags: true
    repo: Stibbons/cfgtree
