# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_temporary_tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 18, 45, 13, 966300, tzinfo=utc)),
        ),
    ]
