sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35

    # Meta
    - python: "3.5"
      env: TOXENV=flake8
    - python: "3.5"
      env: TOXENV=manifest
    - python: "3.5"
      env: TOXENV=docs
    - python: "3.5"
      env: TOXENV=readme


install:
  - pip install tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov

