# coding: utf-8

"""
    RadioManager

    RadioManager

    OpenAPI spec version: 2.0
    Contact: support@pluxbox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import radiomanager_sdk
from radiomanager_sdk.rest import ApiException
from radiomanager_sdk.models.internal_server_error import InternalServerError


class TestInternalServerError(unittest.TestCase):
    """ InternalServerError unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInternalServerError(self):
        """
        Test InternalServerError
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = radiomanager_sdk.models.internal_server_error.InternalServerError()
        pass


if __name__ == '__main__':
    unittest.main()
