# coding: utf-8

"""
    RadioManager

    RadioManager

    OpenAPI spec version: 2.0
    Contact: support@pluxbox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import radiomanager_sdk
from radiomanager_sdk.rest import ApiException
from radiomanager_sdk.models.item_input_only import ItemInputOnly


class TestItemInputOnly(unittest.TestCase):
    """ ItemInputOnly unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemInputOnly(self):
        """
        Test ItemInputOnly
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = radiomanager_sdk.models.item_input_only.ItemInputOnly()
        pass


if __name__ == '__main__':
    unittest.main()
