__version__ = "1.1"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v1.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'f59599eb4de8f8548bc0a52fa5a7e55fed29db80'
__git_head_subject__ = u'Finished Release v1.1'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2018-02-07 14:54:33'
