# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventQueueModel',
            fields=[
                ('attempt', models.PositiveIntegerField(auto_created=True, default=0)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exchange', models.CharField(max_length=50, null=True)),
                ('exchange_type', models.CharField(max_length=50, null=True)),
                ('queue', models.CharField(max_length=50, null=True)),
                ('correlation_id', models.CharField(max_length=36, null=True)),
                ('payload', models.TextField(null=True)),
                ('event_type', models.PositiveSmallIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'event_queue',
            },
        ),
    ]
