# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventqueuemodel',
            name='routing_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventqueuemodel',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Receive'), (2, 'Send')], default=0),
        ),
        migrations.AlterField(
            model_name='eventqueuemodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Opened'), (1, 'Closed')], default=0),
        ),
    ]
