# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_queue', '0002_auto_20171123_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventqueuemodel',
            name='task_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
