# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_queue', '0003_eventqueuemodel_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventqueuemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
