# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_queue', '0005_auto_20171214_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventqueuemodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Opened'), (1, 'Closed'), (2, 'Cancelled'), (3, 'Max attempt')], default=0),
        ),
        migrations.AddIndex(
            model_name='eventqueuemodel',
            index=models.Index(fields=['routing_key', 'updated_at'], name='event_queue_routing_6f58f0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventqueuemodel',
            index=models.Index(fields=['status'], name='event_queue_status_569334_idx'),
        ),
    ]
