"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['SlideRunner.py']
APP_NAME = 'SlideRunner'
DATA_FILES = ['artwork']
OPTIONS = {'argv_emulation': True,
 'iconfile': 'artwork/SlideRunner.icns',
 'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "SlideRunner - An Open Source Annotation Tool for Digital Histology Slides",
        'CFBundleIdentifier': "de.fau.cs5.sliderunner",
        'CFBundleVersion': "1.7.1",
        'CFBundleShortVersionString': "1.7.1",
        'NSHumanReadableCopyright': u"Written by Marc Aubreville (marc.aubreville@fau.de), GPL-licensed"
 }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
